### PR TITLE
WIP attempt to use simpler gh-pages package

### PR DESCRIPTION
**Pull request by erikjung**
@tylersticka FYI, this is what I attempted earlier.

If you could try this and confirm my sanity:
1. Pull this branch
2. Run `npm start`
3. Are your asset paths broken when viewing http://localhost:3000 ?

### CODE REVIEW

**Comment by erikjung** [comment]
Thought it might be that `cdw` typo, but no, same results after fixing it and running `gulp --dev`:

screen shot 2016-06-08 at 11 43 56 am

Might need to examine `{{baseurl}}` a bit.

**Comment by tylersticka** [comment]
I'll give it a whirl!

**Comment by tylersticka** [comment]
@erikjung I can replicate this issue. If you view the page source, every path (including `href` attributes) has `dist/` prepended.

**Comment by erikjung** [comment]
@tylersticka Interesting, isn't it? Since the `demo` task doesn't even need to be executed.

**Pull request closed without merging**
