### PR TITLE
Docs (as-is)

### PR DESCRIPTION
**Pull request by erikjung**
Per the decision to roll with the docs in their WIP state, here they be.
### TODO (high-level)
- [ ] Do all of the TODOs
- [ ] Verify the accuracy of everything
- [ ] Split into multiple pages
- [ ] Add a TOC (or menu, I suppose) for those pages
- [ ] Include automated API docs for helpers?
- [ ] Create issues from this adhoc task list?

/CC @nicolemors @aileenjeffries

### CODE REVIEW

**Comment by tylersticka** [comment]
LGTM :+1:

**Comment by gerardo-rodriguez** [comment]
LGTM! 👍

**Comment by aileenjeffries** [comment]
:+1:

**Comment by saralohr** [comment]
Nice work! 👍

**Pull request merged**
